//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarLab.Shared.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StarLab.Shared.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About StarLab.
        /// </summary>
        public static string AboutStarLab {
            get {
                return ResourceManager.GetString("AboutStarLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Chart.
        /// </summary>
        public static string AddChart {
            get {
                return ResourceManager.GetString("AddChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Document.
        /// </summary>
        public static string AddDocument {
            get {
                return ResourceManager.GetString("AddDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Table.
        /// </summary>
        public static string AddTable {
            get {
                return ResourceManager.GetString("AddTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axes.
        /// </summary>
        public static string Axes {
            get {
                return ResourceManager.GetString("Axes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X1.
        /// </summary>
        public static string AxisX1 {
            get {
                return ResourceManager.GetString("AxisX1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X2.
        /// </summary>
        public static string AxisX2 {
            get {
                return ResourceManager.GetString("AxisX2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y1.
        /// </summary>
        public static string AxisY1 {
            get {
                return ResourceManager.GetString("AxisY1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y2.
        /// </summary>
        public static string AxisY2 {
            get {
                return ResourceManager.GetString("AxisY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Colour.
        /// </summary>
        public static string BackColour {
            get {
                return ResourceManager.GetString("BackColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart.
        /// </summary>
        public static string Chart {
            get {
                return ResourceManager.GetString("Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid content type: {0}.
        /// </summary>
        public static string ChildViewNotAControl {
            get {
                return ResourceManager.GetString("ChildViewNotAControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contents of the clipboard could not be pasted into the folder &apos;{0}&apos;..
        /// </summary>
        public static string ClipboardContentsCouldNotBePasted {
            get {
                return ResourceManager.GetString("ClipboardContentsCouldNotBePasted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Workspace.
        /// </summary>
        public static string CloseWorkspace {
            get {
                return ResourceManager.GetString("CloseWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All Descendants.
        /// </summary>
        public static string CollapseAllDescendants {
            get {
                return ResourceManager.GetString("CollapseAllDescendants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colour.
        /// </summary>
        public static string Colour {
            get {
                return ResourceManager.GetString("Colour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A command with the name &apos;{1}&apos; already exists..
        /// </summary>
        public static string CommandAlreadyExists {
            get {
                return ResourceManager.GetString("CommandAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stratosoft.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2024 All rights reserved etc..
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string DefaultFolderName {
            get {
                return ResourceManager.GetString("DefaultFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move &apos;{0}&apos;. The destination folder is the same as the source folder..
        /// </summary>
        public static string DestinationSameAsSource {
            get {
                return ResourceManager.GetString("DestinationSameAsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document with the name &apos;{0}&apos; already exists..
        /// </summary>
        public static string DocumentAlreadyExists {
            get {
                return ResourceManager.GetString("DocumentAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document could not be created..
        /// </summary>
        public static string DocumentCouldNotBeCreated {
            get {
                return ResourceManager.GetString("DocumentCouldNotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document with the name &apos;{0}&apos; could not be deleted..
        /// </summary>
        public static string DocumentCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("DocumentCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rename &apos;{0}&apos; to &apos;{1}&apos; because a document with that name already exists..
        /// </summary>
        public static string DocumentCouldNotBeRenamed {
            get {
                return ResourceManager.GetString("DocumentCouldNotBeRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document with the name &apos;{0}&apos; will be deleted permanently..
        /// </summary>
        public static string DocumentDeletionWarning {
            get {
                return ResourceManager.GetString("DocumentDeletionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document ID.
        /// </summary>
        public static string DocumentID {
            get {
                return ResourceManager.GetString("DocumentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to replace it?.
        /// </summary>
        public static string DoYouWantToReplaceIt {
            get {
                return ResourceManager.GetString("DoYouWantToReplaceIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} could not be opened..
        /// </summary>
        public static string FileCouldNotBeOpened {
            get {
                return ResourceManager.GetString("FileCouldNotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} could not be found.
        ///Check the filename and try again..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder already contains a folder called &apos;{0}&apos;.
        ///
        ///If documents in the existing folder have the same names as documents in the folder you are copying, do you want to replace the existing documents?.
        /// </summary>
        public static string FolderAlreadyExists {
            get {
                return ResourceManager.GetString("FolderAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder could not be added to the folder &apos;{0}&apos;..
        /// </summary>
        public static string FolderCouldNotBeAdded {
            get {
                return ResourceManager.GetString("FolderCouldNotBeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; could not be deleted..
        /// </summary>
        public static string FolderCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("FolderCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rename &apos;{0}&apos; to &apos;{1}&apos; because a folder with that name already exists..
        /// </summary>
        public static string FolderCouldNotBeRenamed {
            get {
                return ResourceManager.GetString("FolderCouldNotBeRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder &apos;{0}&apos; and all of its contents will be deleted permanently..
        /// </summary>
        public static string FolderDeletionWarning {
            get {
                return ResourceManager.GetString("FolderDeletionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground Colour.
        /// </summary>
        public static string ForeColour {
            get {
                return ResourceManager.GetString("ForeColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string Grid {
            get {
                return ResourceManager.GetString("Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item with key &apos;{0}&apos; is not valid for the current operation..
        /// </summary>
        public static string InvalidOperation {
            get {
                return ResourceManager.GetString("InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The presenter ID does not match the view ID. Expected: {0}.
        /// </summary>
        public static string InvalidPresenterID {
            get {
                return ResourceManager.GetString("InvalidPresenterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Grid Lines.
        /// </summary>
        public static string MajorGridLines {
            get {
                return ResourceManager.GetString("MajorGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Tick Marks.
        /// </summary>
        public static string MajorTickMarks {
            get {
                return ResourceManager.GetString("MajorTickMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Grid Lines.
        /// </summary>
        public static string MinorGridLines {
            get {
                return ResourceManager.GetString("MinorGridLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor Tick Marks.
        /// </summary>
        public static string MinorTickMarks {
            get {
                return ResourceManager.GetString("MinorTickMarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} with the name &apos;{1}&apos; already exists at this location.
        ///Please provide a unique name for the {0}..
        /// </summary>
        public static string NameAlreadyExists {
            get {
                return ResourceManager.GetString("NameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} name cannot be null or empty..
        /// </summary>
        public static string NameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("NameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} names cannot include any of the following:
        ///
        ///                              \ / : * ? &apos; &quot; &lt; &gt; |
        ///
        ///Please enter a valid name..
        /// </summary>
        public static string NameContainsIllegalCharacters {
            get {
                return ResourceManager.GetString("NameContainsIllegalCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} has not been initialised..
        /// </summary>
        public static string NotInitialised {
            get {
                return ResourceManager.GetString("NotInitialised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Workspace.
        /// </summary>
        public static string OpenWorkspace {
            get {
                return ResourceManager.GetString("OpenWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Setup.
        /// </summary>
        public static string PageSetup {
            get {
                return ResourceManager.GetString("PageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot Area.
        /// </summary>
        public static string PlotArea {
            get {
                return ResourceManager.GetString("PlotArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview.
        /// </summary>
        public static string PrintPreview {
            get {
                return ResourceManager.GetString("PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project {0} could not be deleted..
        /// </summary>
        public static string ProjectCouldNotBeDeleted {
            get {
                return ResourceManager.GetString("ProjectCouldNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project &apos;{0}&apos; will be deleted permanently..
        /// </summary>
        public static string ProjectDeletionWarning {
            get {
                return ResourceManager.GetString("ProjectDeletionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save All.
        /// </summary>
        public static string SaveAll {
            get {
                return ResourceManager.GetString("SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Workspace.
        /// </summary>
        public static string SaveWorkspace {
            get {
                return ResourceManager.GetString("SaveWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StarLab.
        /// </summary>
        public static string StarLab {
            get {
                return ResourceManager.GetString("StarLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync With Active Document.
        /// </summary>
        public static string SyncWithActiveDocument {
            get {
                return ResourceManager.GetString("SyncWithActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tick Labels.
        /// </summary>
        public static string TickLabels {
            get {
                return ResourceManager.GetString("TickLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Help.
        /// </summary>
        public static string ViewHelp {
            get {
                return ResourceManager.GetString("ViewHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace.
        /// </summary>
        public static string Workspace {
            get {
                return ResourceManager.GetString("Workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workspace contains items with unsaved changes. Do you want to save your changes?.
        /// </summary>
        public static string WorkspaceClosing {
            get {
                return ResourceManager.GetString("WorkspaceClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} could not be opened..
        /// </summary>
        public static string WorkspaceCouldNotBeOpened {
            get {
                return ResourceManager.GetString("WorkspaceCouldNotBeOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workspace could not be renamed..
        /// </summary>
        public static string WorkspaceCouldNotBeRenamed {
            get {
                return ResourceManager.GetString("WorkspaceCouldNotBeRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rename &apos;{0}&apos; to &apos;{1}&apos; because a workspace with that name already exists at this location..
        /// </summary>
        public static string WorkspaceCouldNotBeRenamedAsAlreadyExists {
            get {
                return ResourceManager.GetString("WorkspaceCouldNotBeRenamedAsAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The workspace could not be saved..
        /// </summary>
        public static string WorkspaceCouldNotBeSaved {
            get {
                return ResourceManager.GetString("WorkspaceCouldNotBeSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace Explorer.
        /// </summary>
        public static string WorkspaceExplorer {
            get {
                return ResourceManager.GetString("WorkspaceExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.slw)|*.slw.
        /// </summary>
        public static string WorkspaceFileFilter {
            get {
                return ResourceManager.GetString("WorkspaceFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
